language: python
python:
  - "3.6"
  - "3.6.7"
  - "3.6-dev"
  - "3.7.0"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest